version: "3.8"

services:
  # App proxy and LB
  app-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/primary/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - backend-proxy
    networks:
      - app-network


  frontend:
    build:
      context: ./frontend
    entrypoint: npm start
    ports:
      - 3000:3000
    networks:
      - app-network

  #PHP Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  backend-proxy:
    image: nginx:alpine
    container_name: webserver
    # tty: true
    # ports:
    #   - "8080:8080"
    volumes:
      - ./backend:/var/www
      - ./nginx/backend/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:

    driver: local
